version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chargemasterapi_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        environment:
            - "APP_ENV=local"
            - "APP_DEBUG=true"
            - "APP_KEY=base64:1YRyaTum5XFqCfcbDbKCsKkAmsXTzYGtZxep3abW/nI="
            - "APP_URL=http://chargemasterapi.conf.local"
            - "DB_CONNECTION=mysql"
            - "DB_HOST=db"
            - "DB_PORT=3306"
            - "DB_DATABASE=chargemasterapi.conf"
            - "DB_USERNAME=your_db_user_here"
            - "DB_PASSWORD=your_db_password_here"
        depends_on:
            - db
        networks:
            - chargemasterapi

    db:
        image: mysql:5.7
        container_name: chargemasterapi_db
        restart: unless-stopped
        environment:
            - "MYSQL_DATABASE=chargemasterapi.conf"
            - "MYSQL_USER=your_db_user_here"
            - "MYSQL_PASSWORD=your_db_password_here"
            - "MYSQL_ROOT_PASSWORD=your_mysql_root_password_here"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - chargemasterapi
    nginx:
        image: nginx:stable-alpine
        container_name: chargemasterapi_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - chargemasterapi

networks:
    chargemasterapi:
        driver: bridge

volumes:
    dbdata:
        driver: local
