version: '3'
services:
    php:
        build:
            context: .

        volumes:
            - .:/var/www/html
    web:
        image: nginx:1.17
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   "80:80"
    db:
        image: mysql:8
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: 'radu'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
             - "3306:3306"
        expose:
            -   "3306"
volumes:
    mysql-data:
